Biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('livros.urls', namespace='livros')),

    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Biblioteca/livros/urls.py
from django.urls import path
from . import views

app_name = 'livros'


urlpatterns =[

    path(r'', views.index, name='index'),

    path(r'lista/', views.lista, name='lista'),

    path(r'cria/', views.cria, name='cria'),

    path(r'atualizar/', views.atualizar, name='atualizar'),

    path(r'detalhes/', views.detalhes, name='detalhes'),

]

Biblioteca/livros/models.py
from django.db import models



class Livro(models.Model):

    nome = models.CharField(max_length=50, unique=True)

    categoria = models.CharField(max_length=30)

    capa = models.ImageField(upload_to='capa_livro')

    autor = models.CharField(max_length=30, null=True)

    data_publicacao = models.DateField()

    pag = models.IntegerField(default=0)

Biblioteca/livros/forms.py
from django import forms
from .models import Livro


class LivroForm(forms.ModelForm):

    class Meta:
        model = Livro
        fields = '__all__'

Biblioteca/livros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from livros.models import Livro
from livros.forms import LivroForm
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'index.html')


def cria(request):
    if request.method == "POST":
        form = LivroForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print
            'Livro adicionado com sucesso !'
            return redirect('livros.views.lista')
    else:
        form = LivroForm()
    return render(request, 'cria.html', {'form': form})


def detalhes(request, pk):
    post = get_object_or_404(Livro, pk=pk)
    return render(request, 'detalhes.html', {'post': post})


def atualizar(request, pk):
    post = get_object_or_404(Livro, pk=pk)
    if request.method == "GET":
        form = LivroForm(request.GET, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('livro.views.detalhes', pk=post.pk)
    else:
        form = LivroForm(instance=post)
    return render(request, 'atualiza.html', {'form': form})


def excluir(request, pk):
    post = get_object_or_404(Livro, pk=pk).delete()
    redirect('livros.views.detalhes')
    return render(request, 'exclui.html', {'post': post})


def lista(request):
    livros = Livro.objects.all()
    return render(request, 'lista.html', locals())

Biblioteca/livros/templates/_layouts/base.html
<!DOCTYPE html>
<html>

     {% load static %}

     <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Sistema de Gerenciamento de Livros{% endblock %}</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/logo.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static
        'css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-blue bg-blue">
            <a class="navbar-brand" href="{% url 'livros:index' %}">
              <img src="{% static 'img/logo.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'livros:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'livros:lista' %}">Livros</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b></b></a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

Biblioteca/livros/templates/atualiza.html
{% extends "_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Livros{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Livros</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CPF</span>
              </div>
              {% render_field form.cpf class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Remuneração -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Remuneração</span>
              </div>
              {% render_field form.remuneracao class+="form-control" %}
            </div>
            <hr />
            <div class="text-right">
              <a href="{% url 'livros:lista' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Biblioteca/livros/templates/cria.html
{% extends "_layouts/base.html" %}

{% block title %}Cadastro de Livros{% endblock %}

{% block conteudo %}


    <div class="container mt-5">
         <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                 <div class="card">
                     <div class="card-body">
                         <h5 class="card-title">Cadastro de Livro</h5>
                            <p class="card-text">
                              Complete o Formulário abaixo para cadastrar
                              um novo <code>Livro</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag - Proteção do Formulario -->
            {% csrf_token %}
              {{ form.as_p }}
            <hr>
            <div class="text-right">
              <a href="{% url 'livros:index' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Biblioteca/livros/templates/detalhes.html
{% extends 'site/base.html' %}
{% load staticfiles %}
{% block content %}
  <main class="container">
  	<h3 class="title"> Detalhes do livros</h3>
    	<section id="details">


			<label>Nome: </label>{{post.nome}}<br/>
            <label>Categoria:</label>{{post.categoria}}<br/>
            <label>Capa:</label>{{post.capa}}<br/>
			<label>Autor: </label>{{post.autor}}<br/>
			<label>Data Publicaçao: </label>{{post.data_publicacao}}<br/>
			<label>Paginas: </label>{{post.numero_paginas}}</p><br/>

			<a href="{% url 'livros.views.atualiza' pk=post.pk %}">
				<img src="{% static 'img/update.png' %}" /> Alterar
			</a>
			<button class="button-back"  onclick="new MyQuestion('Deseja realmente excluir o livro {{ post.nome }}',
    '{% url 'livros.views.exclui' pk=post.pk %}').question()">
				<img src="{% static 'img/delete.png' %}" /> Excluir
			</button>
			<a href="{% url 'livros.views.lista' %}">
				<img src="{% static 'img/back.png' %}"> Voltar
			</a>
		</section>

    </main>
{% endblock %}

Biblioteca/livros/templates/exclui.html
<!-- Estendemos do template base -->
{% extends "_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}

  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Livro</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o livro <b>{{ livro.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'livros:lista' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Biblioteca/livros/templates/index.html
<!-- Estendemos do template base -->
{% extends "_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
      <div class="container mt-5">
          <div class="row">
             <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cadastrar Livros</h5>
                        <p class="card-text">
                            Cadastre Aqui Um Novo <code>Livro</code>   </p>
                        <a href="{% url 'livros:cria' %}" class="btn btn-primary">
                            Novo Livro
                        </a>
                    </div>
                </div>
             </div>

             <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                 <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Lista de Livros</h5>
                           <p class="card-text">
                            Veja aqui a lista de Todos os <code>Livros</code> cadastrados.
                            </p>
                    <a href="{% url 'livros:lista' %}"  class="btn btn-primary">
                      Vá para Lista
                    </a>
             </div>
                </div>
                  </div>
              </div>
      </div>
{% endblock %}

Biblioteca/livros/templates/lista.html
{% extends "_layouts/base.html" %}

{% block title %}Cadastro de Livros{% endblock %}

{% block conteudo %}

  <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                       <h5 class="card-title">Lista de Livros</h5>
                               {% if livros|length > 0 %}
                       <p class="card-text">
                           Aqui está a lista de <code>Livros</code> cadastrados.
                       </p>
                       <table class="table">
                           <thead class="thead-dark">
                       <tr>
                          <th scope="col"></th>
                          <th scope="col">Nome</th>
                          <th scope="col">Categoria</th>
                          <th scope="col">Capa</th>
                          <th scope="col">Autor</th>
                          <th scope="col">Data</th>
                          <th scope="col">Paginas</th>
                          <th scope="col" class="text-center">Ações</th>
                       </tr>
                           </thead>
                       <tbody>
                       {% for l in livros %}
                       <tr>
                           <th scope="row">{{ l.id }}</th>
                           <td>{{ l.nome }}</td>
                           <td>{{ l.categoria }}</td>
                           <td>{{ l.capa}}</td>
                           <td>{{ l.autor }}</td>
                           <td>{{ l.data_publicacao }}</td>
                           <td>{{ l.pag }}</td>
                           <td class="text-center">

                             <a href="{% url 'livros:atualizar' pk='l.pk' %}"
                             class="btn btn-primary"> Atualizar </a>
                             <a href="{% url 'livros:exclui' pk='l.pk' %}"
                              class="btn btn-danger"> Excluir </a>
                           </td>
                       </tr>
                             {% endfor %}
                           </tbody>
                    </table>
        {% else %}
                       <div class="text-center mt-5 mb-5 jumbotron">
                           <h5>Nenhum <code>Livro</code> cadastrado ainda.</h5>
                       </div>
        {% endif %}
                      <hr />
                      <div class="text-right">
                         <a href="{% url 'livros:cria' %}" class="btn btn-primary">
                           Cadastrar Livro </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}